Education Portal/EducationPortal/EducationPortal.UI/Models/ViewEntities/Materials/ArticleView.cs
using System.ComponentModel.DataAnnotations;

namespace EducationPortal.UI.Models.ViewEntities
{
    public class ArticleView : MaterialView
    {
        [Required(ErrorMessage = "Not specified sourse")]
        public string Source { get; set; }

        [Required(ErrorMessage = "Not specified data")]
        public DateTime PublicationDate { get; set; }
    }
}

Education Portal/EducationPortal/EducationPortal.UI/Models/ViewEntities/Materials/BookView.cs
using System.ComponentModel.DataAnnotations;

namespace EducationPortal.UI.Models.ViewEntities
{
    public class BookView : MaterialView
    {
        [Required(ErrorMessage = "Not specified number of pages")]
        public int NumberPages { get; set; }

        [Required(ErrorMessage = "Not specified format")]
        public string Format { get; set; }

        [Required(ErrorMessage = "Not specified author")]
        public string Author { get; set; }

        [Required(ErrorMessage = "Not specified publication date")]
        public DateTime PublicationDate { get; set; }
    }
}

Education Portal/EducationPortal/EducationPortal.UI/Models/ViewEntities/Materials/MaterialSelectView.cs
namespace EducationPortal.UI.Models.ViewEntities.Materials
{
    public class MaterialSelectView
    {
        public MaterialView Material { get; set; }

        public string Name { get; set; }
    }
}

Education Portal/EducationPortal/EducationPortal.UI/Models/ViewEntities/Materials/MaterialView.cs
using EducationPortal.UI.Models.Common;
using System.ComponentModel.DataAnnotations;

namespace EducationPortal.UI.Models.ViewEntities
{
    public class MaterialView : BaseViewEntity
    {
        [Required(ErrorMessage = "Not specified name")]
        public string Name { get; set; }
    }
}

Education Portal/EducationPortal/EducationPortal.UI/Models/ViewEntities/Materials/VideoView.cs
using System.ComponentModel.DataAnnotations;

namespace EducationPortal.UI.Models.ViewEntities
{
    public class VideoView : MaterialView
    {
        [Required(ErrorMessage = "Not specified duration")]
        public TimeSpan Duration { get; set; }

        [Required(ErrorMessage = "Not specified quality")]
        public string Quality { get; set; }
    }
}

Education Portal/EducationPortal/EducationPortal.UI/Controllers/EditingMaterialsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EducationPortal.UI.Controllers
{
    [Authorize]
    public class EditingMaterialsController : Controller
    {
        private readonly IMaterialEditService _materialService;

        public EditingMaterialsController(IMaterialEditService materialService)
        {
            _materialService = materialService;
        }

        public async Task<IActionResult> Materials()
        {
            var materials = await _materialService.GetMaterials();
            return View(materials);
        }

        public IActionResult CreateArticle()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateArticle(ArticleView material)
        {
            if (ModelState.IsValid)
            {
                if (material.Id == 0)
                {
                    await _materialService.SetArticle(material);
                }

                return RedirectToAction("Materials");
            }

            return View();
        }

        public IActionResult CreateBook()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBook(BookView material)
        {
            if (ModelState.IsValid)
            {
                if (material.Id == 0)
                {
                    await _materialService.SetBook(material);
                }

                return RedirectToAction("Materials");
            }

            return View();
        }

        public IActionResult CreateVideo()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateVideo(VideoView material)
        {
            if (ModelState.IsValid)
            {
                if (material.Id == 0)
                {
                    await _materialService.SetVideo(material);
                }

                return RedirectToAction("Materials");
            }

            return View();
        }

        public async Task<IActionResult> EditArticle(int? id)
        {
            if (ModelState.IsValid)
            {
                ArticleView? material = await _materialService.GetByIdArticle(id ?? 0);
                if (material != null)
                {
                    return View(material);
                }

                return NotFound();
            }

            return View(id);
        }

        public async Task<IActionResult> EditBook(int? id)
        {
            if (ModelState.IsValid)
            {
                BookView? material = await _materialService.GetByIdBook(id ?? 0);
                if (material != null)
                {
                    return View(material);
                }

                return NotFound();
            }

            return View(id);
        }

        public async Task<IActionResult> EditVideo(int? id)
        {
            if (ModelState.IsValid)
            {
                VideoView? material = await _materialService.GetByIdVideo(id ?? 0);
                if (material != null)
                {
                    return View(material);
                }

                return NotFound();
            }

            return View(id);
        }

        [HttpPost]
        public async Task<IActionResult> EditArticle(ArticleView material)
        {
            await _materialService.UpdateArticle(material);

            return RedirectToAction("Materials");
        }

        [HttpPost]
        public async Task<IActionResult> EditBook(BookView material)
        {
            await _materialService.UpdateBook(material);

            return RedirectToAction("Materials");
        }

        [HttpPost]
        public async Task<IActionResult> EditVideo(VideoView material)
        {
            await _materialService.UpdateVideo(material);

            return RedirectToAction("Materials");
        }

        public async Task<IActionResult> DeleteArticle(int? id)
        {
            ArticleView? material = await _materialService.GetByIdArticle(id ?? 0);
            if (material != null)
            {
                await _materialService.RemoveArticle(material);
                return RedirectToAction("Materials");
            }

            return NotFound();
        }

        public async Task<IActionResult> DeleteBook(int? id)
        {
            BookView? material = await _materialService.GetByIdBook(id ?? 0);
            if (material != null)
            {
                await _materialService.RemoveBook(material);
                return RedirectToAction("Materials");
            }

            return NotFound();
        }

        public async Task<IActionResult> DeleteVideo(int? id)
        {
            VideoView? material = await _materialService.GetByIdVideo(id ?? 0);
            if (material != null)
            {
                await _materialService.RemoveVideo(material);
                return RedirectToAction("Materials");
            }

            return NotFound();
        }

        public async Task<IActionResult> DetailsArticle(int? id)
        {
            ArticleView? material = await _materialService.GetByIdArticle(id ?? 0);
            if (material != null)
            {
                return View(material);
            }

            return NotFound();
        }

        public async Task<IActionResult> DetailsBook(int? id)
        {
            BookView? material = await _materialService.GetByIdBook(id ?? 0);
            if (material != null)
            {
                return View(material);
            }

            return NotFound();
        }

        public async Task<IActionResult> DetailsVideo(int? id)
        {
            VideoView? material = await _materialService.GetByIdVideo(id ?? 0);
            if (material != null)
            {
                return View(material);
            }

            return NotFound();
        }
    }
}

Education Portal/EducationPortal/EducationPortal.UI/Views/EditingMaterials/CreateArticle.cshtml
@model EducationPortal.UI.Models.ViewEntities.ArticleView

<h2>Adding article</h2>
<form asp-action="CreateArticle" asp-controller="EditingMaterials">
    <p>
        <label asp-for="Name">Name</label><br/>
        <input type="text" asp-for="Name" />
        <span asp-validation-for="Name"/>
    </p>
    <p>
        <label asp-for="Source">Source</label><br/>
        <input type="text" asp-for="Source" />
        <span asp-validation-for="Source"/>
    </p>
     <p>
        <label asp-for="PublicationDate">PublicationDate</label><br/>
        <input type="date" asp-for="PublicationDate" />
        <span asp-validation-for="PublicationDate"/>
    </p>
    <p>
        <input type="submit" value="Submit"/>
    </p>
</form>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Education Portal/EducationPortal/EducationPortal.UI/Views/EditingMaterials/CreateBook.cshtml
@model EducationPortal.UI.Models.ViewEntities.BookView

<h2>Adding book</h2>
<form asp-action="CreateBook" asp-controller="EditingMaterials">
    <p>
        <label asp-for="Name">Name</label><br/>
        <input type="text" asp-for="Name" />
        <span asp-validation-for="Name"/>
    </p>
    <p>
        <label asp-for="Author">Author</label><br/>
        <input type="text" asp-for="Author" />
        <span asp-validation-for="Author"/>
    </p>
    <p>
        <label asp-for="Format">Format</label><br/>
        <input type="text" asp-for="Format" />
        <span asp-validation-for="Format"/>
    </p>
    <p>
        <label asp-for="NumberPages">NumberPages</label><br/>
        <input type="number" asp-for="NumberPages" />
        <span asp-validation-for="NumberPages"/>
    </p>
     <p>
        <label asp-for="PublicationDate">PublicationDate</label><br/>
        <input type="date" asp-for="PublicationDate" />
        <span asp-validation-for="PublicationDate"/>
    </p>
    <p>
        <input type="submit" value="Submit"/>
    </p>
</form>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Education Portal/EducationPortal/EducationPortal.UI/Views/EditingMaterials/CreateVideo.cshtml
@model EducationPortal.UI.Models.ViewEntities.VideoView

<h2>Create video</h2>
<form asp-action="CreateVideo" asp-controller="EditingMaterials">
    <p>
        <label asp-for="Name">Name</label><br/>
        <input type="text" asp-for="Name" />
        <span asp-validation-for="Name"/>
    </p>
    <p>
        <label asp-for="Quality">Quality</label><br/>
        <input type="text" asp-for="Quality" />
        <span asp-validation-for="Quality"/>
    </p>
    <p>
        <label asp-for="Duration">Duration</label><br/>
        <input type="time" asp-for="Duration" />
        <span asp-validation-for="Duration"/>
    </p>
    <p>
        <input type="submit" value="Submit"/>
    </p>
</form>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Education Portal/EducationPortal/EducationPortal.UI/Views/EditingMaterials/DetailsArticle.cshtml
@model EducationPortal.UI.Models.ViewEntities.ArticleView
@{
    var item = Model;
}

<h2># @item.Id</h2>
<p>Article name: @item.Name</p>
<p>Sourse: @item.Source</p>
<p>Publication date: @item.PublicationDate</p>
<a class="nav-link text-dark" asp-area="" asp-controller="EditingMaterials" asp-action="Materials">To previous page</a>

Education Portal/EducationPortal/EducationPortal.UI/Views/EditingMaterials/DetailsBook.cshtml
@model EducationPortal.UI.Models.ViewEntities.BookView
@{
    var item = Model;
}
<h2># @item.Id</h2>
<p>Book name: @item.Name</p>
<p>Number of pages: @item.NumberPages</p>
<p>Publication date: @item.PublicationDate</p>
<p>Format: @item.Format</p>
<a class="nav-link text-dark" asp-area="" asp-controller="EditingMaterials" asp-action="Materials">To previous page</a>

Education Portal/EducationPortal/EducationPortal.UI/Views/EditingMaterials/DetailsVideo.cshtml
@model EducationPortal.UI.Models.ViewEntities.VideoView
@{
    var item = Model;
}
<h2># @item.Id</h2>
<p>Video name: @item.Name</p>
<p>Duration: @item.Duration</p>
<p>Quality: @item.Quality</p>
<a class="nav-link text-dark" asp-area="" asp-controller="EditingMaterials" asp-action="Materials">To previous page</a>

Education Portal/EducationPortal/EducationPortal.UI/Views/EditingMaterials/EditArticle.cshtml
@model EducationPortal.UI.Models.ViewEntities.ArticleView

<h2>Editing article</h2>
<form asp-action="EditArticle" asp-controller="EditingMaterials" method="post" asp-route-id="@Model.Id">
    <p>
        <label asp-for="Name">Name</label><br/>
        <input type="text" asp-for="Name" />
        <span asp-validation-for="Name"/>
    </p>
    <p>
        <label asp-for="Source">Source</label><br/>
        <input type="text" asp-for="Source" />  
        <span asp-validation-for="Source"/>
    </p>
     <p>
        <label asp-for="PublicationDate">PublicationDate</label><br/>
        <input type="date" asp-for="PublicationDate" />
        <span asp-validation-for="PublicationDate"/>
    </p>
    <p>
        <input type="submit" value="Submit"/>
    </p>
</form>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Education Portal/EducationPortal/EducationPortal.UI/Views/EditingMaterials/EditBook.cshtml
@model EducationPortal.UI.Models.ViewEntities.BookView

<h2>Editing book</h2>
<form asp-action="EditBook" asp-controller="EditingMaterials" method="post" asp-route-id="@Model.Id">
    <p>
        <label asp-for="Name">Name</label><br/>
        <input type="text" asp-for="Name" />
        <span asp-validation-for="Name"/>
    </p>
    <p>
        <label asp-for="Author">Author</label><br/>
        <input type="text" asp-for="Author" />
        <span asp-validation-for="Author"/>
    </p>
    <p>
        <label asp-for="Format">Format</label><br/>
        <input type="text" asp-for="Format" />
        <span asp-validation-for="Format"/>
    </p>
    <p>
        <label asp-for="NumberPages">NumberPages</label><br/>
        <input type="number" asp-for="NumberPages" />
        <span asp-validation-for="NumberPages"/>
    </p>
     <p>
        <label asp-for="PublicationDate">PublicationDate</label><br/>
        <input type="date" asp-for="PublicationDate" />
        <span asp-validation-for="PublicationDate"/>
    </p>
    <p>
        <input type="submit" value="Submit"/>
    </p>
</form>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Education Portal/EducationPortal/EducationPortal.UI/Views/EditingMaterials/EditVideo.cshtml
@model EducationPortal.UI.Models.ViewEntities.VideoView

<h2>Editing video</h2>
<form asp-action="EditVideo" asp-controller="EditingMaterials" method="post" asp-route-id="@Model.Id">
    <p>
        <label asp-for="Name">Name</label><br/>
        <input type="text" asp-for="Name" />
        <span asp-validation-for="Name"/>
    </p>
    <p>
        <label asp-for="Quality">Quality</label><br/>
        <input type="text" asp-for="Quality" />
        <span asp-validation-for="Quality"/>
    </p>
    <p>
        <label asp-for="Duration">Duration</label><br/>
        <input type="time" asp-for="Duration" />
        <span asp-validation-for="Duration"/>
    </p>
    <p>
        <input type="submit" value="Submit"/>
    </p>
</form>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Education Portal/EducationPortal/EducationPortal.UI/Views/EditingMaterials/Materials.cshtml
@model IEnumerable<MaterialView>

 <h3>Material list</h3>
<table class="table">
    <tr><th>#</th><th>Type</th><th>Title</th><th></th><th></th></tr>
    @foreach (var item in Model)
        {
         <tr>
             <td>@item.Id</td>
            @if (item is BookView)
            {
                <td>Book</td>
            }
            else if (item is VideoView)
            {
                 <td>Video</td>
            }
            else if (item is ArticleView)
            {
                 <td>Article</td>
            }
            <td>@item.Name</td>
            @if (item is BookView)
            {
                <td>
                    <a asp-controller="EditingMaterials" asp-action="EditBook" asp-route-id="@item.Id">Change</a> |  <a asp-controller="EditingMaterials" asp-action="DetailsBook" asp-route-id="@item.Id">Details</a>
                </td>
                <td>
                    <form asp-controller="EditingMaterials" asp-action="DeleteBook" asp-route-id="@item.Id">
                        <input type="submit" value="Delete" />
                    </form>
                </td>
            }
            else if (item is VideoView)
            {
                <td>
                    <a asp-controller="EditingMaterials" asp-action="EditVideo" asp-route-id="@item.Id">Change</a> |  <a asp-controller="EditingMaterials" asp-action="DetailsVideo" asp-route-id="@item.Id">Details</a>
                </td>
                <td>
                    <form asp-controller="EditingMaterials" asp-action="DeleteVideo" asp-route-id="@item.Id">
                        <input type="submit" value="Delete" />
                    </form>
                </td>
            }
            else if (item is ArticleView)
            {
                <td>
                    <a asp-controller="EditingMaterials" asp-action="EditArticle" asp-route-id="@item.Id">Change</a> |  <a asp-controller="EditingMaterials" asp-action="DetailsArticle" asp-route-id="@item.Id">Details</a>
                </td>
                <td>
                    <form asp-controller="EditingMaterials" asp-action="DeleteArticle" asp-route-id="@item.Id">
                        <input type="submit" value="Delete" />
                    </form>
                </td>
            }
         </tr>
    }
</table>
<p><a asp-controller="EditingMaterials" asp-action="CreateBook">+ Add Book</a></p>
<p><a asp-controller="EditingMaterials" asp-action="CreateVideo">+ Add Video</a></p>
<p><a asp-controller="EditingMaterials" asp-action="CreateArticle">+ Add Article</a></p>