Education Portal/EducationPortal/EducationPortal.UI/Controllers/EditingCoursesController.cs
using EducationPortal.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;

namespace EducationPortal.UI.Controllers
{
    [Authorize]
    public class EditingCoursesController : Controller
    {
        private readonly ICourseEditService _courseEditService;
        private readonly ICourseSelectListsService _courseSelectListsService;

        public EditingCoursesController(ICourseEditService courseEditService, ICourseSelectListsService courseSelectListsService)
        {
            _courseEditService = courseEditService;
            _courseSelectListsService = courseSelectListsService;
        }

        public async Task<IActionResult> Courses()
        {
            var courses = await _courseEditService.GetCourses();
            return View(courses);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CourseView course)
        {
            if (ModelState.IsValid)
            {
                if (course.Id == 0)
                {
                    await _courseEditService.SetCourse(course);
                }

                return RedirectToAction("Courses");
            }

            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (ModelState.IsValid)
            {
                CourseView? course = await _courseEditService.GetByIdCourse(id ?? 0);
                if (course != null)
                {
                    return View(course);
                }

                return NotFound();
            }

            return View(id);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CourseView course)
        {
            await _courseEditService.UpdateCourse(course);

            return RedirectToAction("Courses");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            CourseView? course = await _courseEditService.GetByIdCourse(id ?? 0);
            if (course != null)
            {
                await _courseEditService.RemoveCourse(course);
                return RedirectToAction("Courses");
            }

            return NotFound();
        }

        public async Task<IActionResult> Details(int? id)
        {
            CourseView? course = await _courseEditService.GetByIdCourse(id ?? 0);
            if (course != null)
            {
                return View(course);
            }

            return NotFound();
        }

        public async Task<IActionResult> AddMaterials(int? id)
        {
            if (id != null)
            {
                var model = await _courseSelectListsService.GetAllMaterialsSelectList((int)id);
                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> AddMaterials(CourseMaterialsView? courseMaterials)
        {
            await _courseEditService.AddMaterialsInCourse(courseMaterials);
            return RedirectToAction("Courses");
        }

        public async Task<IActionResult> AddSkills(int? id)
        {
            if (id != null)
            {
                var model = await _courseSelectListsService.GetAllSkillsSelectList((int)id);
                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> AddSkills(CourseSkillView? courseSkills)
        {
            await _courseEditService.AddSkillsInCourse(courseSkills);
            return RedirectToAction("Courses");
        }
    }
}

Education Portal/EducationPortal/EducationPortal.UI/Controllers/EditingSkillsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EducationPortal.UI.Controllers
{
    [Authorize]
    public class EditingSkillsController : Controller
    {
        private readonly ISkillEditService _skillEditService;

        public EditingSkillsController(ISkillEditService skillEditService)
        {
            _skillEditService = skillEditService;
        }

        public async Task<IActionResult> Skills()
        {
            var skills = await _skillEditService.GetSkills();
            return View(skills);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SkillView skill)
        {
            if (ModelState.IsValid)
            {
                if (skill.Id == 0)
                {
                    await _skillEditService.SetSkill(skill);
                }

                return RedirectToAction("Skills");
            }

            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (ModelState.IsValid)
            {
                SkillView? skill = await _skillEditService.GetByIdSkill(id ?? 0);
                if (skill != null)
                {
                    return View(skill);
                }

                return NotFound();
            }

            return View(id);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SkillView skill)
        {
            await _skillEditService.UpdateSkill(skill);

            return RedirectToAction("Skills");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            SkillView? skill = await _skillEditService.GetByIdSkill(id ?? 0);
            if (skill != null)
            {
                await _skillEditService.RemoveSkill(skill);
                return RedirectToAction("Skills");
            }

            return NotFound();
        }
    }
}

Education Portal/EducationPortal/EducationPortal.UI/Controllers/PassCourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EducationPortal.UI.Controllers
{
    [Authorize]
    public class PassCourseController : Controller
    {
        private readonly IUserCoursePassService _userCoursePassService;

        public PassCourseController(IUserCoursePassService userCoursePassService)
        {
            _userCoursePassService = userCoursePassService;
        }

        public async Task<IActionResult> StartCourse()
        {
            var availableCourses = await _userCoursePassService.AvailableCourses(User.Identity.Name);
            return View(availableCourses);
        }

        public async Task<IActionResult> TakeCourse(int? id)
        {
            await _userCoursePassService.TakeCourse(id, User.Identity.Name);
            return RedirectToAction("StartCourse");
        }

        public async Task<IActionResult> PassCourses()
        {
            var userName = User.Identity.Name;
            var courses = await _userCoursePassService.StartedCourses(userName);
            ViewBag.UserCourses = await _userCoursePassService.StartedCoursesGetStatusInfo(userName);
            return View(courses);
        }

        public async Task<IActionResult> StartPassCourse(int? id)
        {
            var userName = User.Identity.Name;
            if (id != null)
            {
                CourseView course = await _userCoursePassService.GetCourseToPass(id);
                ViewBag.CourseMaterial = await _userCoursePassService.PassedMaterials(id, userName);
                return View(course);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> PassMaterial(int? id, string? name)
        {
            var userName = User.Identity.Name;
            await _userCoursePassService.PassMaterial(id, name, userName);
            return RedirectToAction("StartPassCourse", new { id });
        }

        public async Task<IActionResult> PassedCourses()
        {
            List<CourseView> courses = await _userCoursePassService.PassedCourses(User.Identity.Name);
            return View(courses);
        }
    }
}

Education Portal/EducationPortal/EducationPortal.UI/Controllers/UserInfoController.cs
using EducationPortal.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EducationPortal.UI.Controllers
{
    [Authorize]
    public class UserInfoController : Controller
    {
        private readonly IUserInformationService _userInformation;

        public UserInfoController(IUserInformationService userInformation)
        {
            _userInformation = userInformation;
        }

        [HttpGet]
        public async Task<IActionResult> UserProfile()
        {
            var user = await _userInformation.GetUserInfo(User.Identity.Name);
            ViewBag.AuthorizedUser = user;
            var userSkills = user.UserSkills;
            List<SkillView> skills = new List<SkillView>();
            for (int i = 0; i < userSkills.Count; ++i)
            {
                SkillView? findedSkill = user.Skills.FirstOrDefault(x => x.Id == userSkills[i].SkillId);
                if (findedSkill != null)
                {
                    skills.Add(findedSkill);
                }
            }

            var userCourses = user.UserCourses;
            List<CourseView> courses = new List<CourseView>();
            for (int i = 0; i < userCourses.Count; ++i)
            {
                CourseView? findedCourse = user.Courses.FirstOrDefault(x => x.Id == userCourses[i].CourseId);
                if (findedCourse != null)
                {
                    courses.Add(findedCourse);
                }
            }

            ViewBag.UserSkills = skills;
            ViewBag.UserCourses = courses;
            return View();
        }
    }
}

Education Portal/EducationPortal/EducationPortal.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EducationPortal.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EducationPortal.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EducationPortal.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Help</a>
                        </li>
                        @if(!User.Identity.IsAuthenticated){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Sign in</a>
                        </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserInfo" asp-action="UserProfile">UserProfile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EditingSkills" asp-action="Skills">Skills</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EditingMaterials" asp-action="Materials">Materials</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EditingCourses" asp-action="Courses">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PassCourse" asp-action="StartCourse">StartCourse</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PassCourse" asp-action="PassCourses">PassingCourse</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PassCourse" asp-action="PassedCourses">PassedCourses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Sign out</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>